import React from 'react'
import styles from './styles.module.css'
import Button from './../../ui/button'

const Numbers = ({clickHandler}) => {
	return (
		<div className={styles.numbers}>
			<div>	
				<Button 
					clicked={clickHandler}
					btnType="key"
					value="1">1</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="2">2</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="3">3</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="&">&</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="#">#</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="(">(</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value=")">)</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="4">4</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="5">5</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="6">6</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="@">@</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="!">!</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="?">?</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value=":">:</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="7">7</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="8">8</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="9">9</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="0">0</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value=".">.</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="_">_</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value='"'>"</Button>
			</div>
		</div>
	)
}

export default Numbers