import React from 'react'
import styles from './styles.module.css'
import Button from './../../ui/button'

const Alphabets = ({clickHandler}) => {
	return (
		<div className={styles.alphabets}>
			<div>	
				<Button 
					clicked={clickHandler}
					btnType="key"
					value="A">A</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="B">B</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="C">C</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="D">D</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="E">E</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="F">F</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="G">G</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="H">H</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="I">I</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="J">J</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="K">K</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="L">L</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="M">M</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="N">N</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="O">O</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="P">P</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="Q">Q</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="R">R</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="S">S</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="T">T</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="U">U</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="V">V</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="W">W</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="X">X</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="Y">Y</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="Z">Z</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="-">-</Button>
			</div>
			<div>
				<Button
					clicked={clickHandler}
					btnType="key"
					value="'">'</Button>
			</div>
		</div>
	)
}

export default Alphabets